#ifndef rftrace_frontend_ffi_h
#define rftrace_frontend_ffi_h

/* Generated with cbindgen:0.14.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Used to keep track of event buffer given to the staticlib
 */
typedef struct Events Events;

void rftrace_disable(void);

int64_t rftrace_dump_full_uftrace(Events *events,
                                  const char *out_dir,
                                  const char *binary_name,
                                  uint64_t linux_mode);

int64_t rftrace_dump_trace(Events *events, const char *outfile);

void rftrace_enable(void);

Events *rftrace_init(uintptr_t max_event_count, bool overwriting);

#endif /* rftrace_frontend_ffi_h */
